apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agro-tech-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:

      - path: /v1/api/auth
        pathType: Prefix
        backend:
          service:
            name: agtc-srv-auth
            port:
              number: 80

      - path: /v1/api/properties
        pathType: Prefix
        backend:
          service:
            name: agtc-srv-management
            port:
              number: 80

      - path: /v1/api/sensors 
        pathType: Prefix
        backend:
          service:
            name: agtc-srv-management
            port:
              number: 80

      - path: /v1/api/telemetry
        pathType: Prefix
        backend:
          service:
            name: agtc-srv-ingestion
            port:
              number: 80

      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-service
            port:
              number: 80