apiVersion: v1
kind: Secret
metadata:
  name: secrets-ms-analysis
type: Opaque
stringData:
  ConnectionStrings__MongoDbConnection: ${MONGO_CONNECTION_STRING_GITHUB}
  Jwt__SigningKey: ${JWT_SIGNING_KEY_GITHUB}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY_GITHUB}
  ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT_GITHUB}
  AWS_REGION: ${AWS_REGION_GITHUB}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_GITHUB}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_GITHUB}
