apiVersion: v1
kind: Secret
metadata:
  name: secrets-ms-management
type: Opaque
stringData:
  ConnectionStrings__MongoDbConnection: ${MONGO_CONNECTION_STRING_GITHUB}
  Jwt__SigningKey: ${JWT_SIGNING_KEY_GITHUB}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY_GITHUB}
  ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT_GITHUB}